main: de.xcrafttm.borderxp.Main
name: BorderXP
version: 1.1
api-version: 1.17
author: XCraftTM
website: github.com/XCraftTM/BorderXP

commands:
  bordertoggle:
    aliases: bt
    description: Toggle BorderXP Challenge
    usage: /<command>