main: de.xcrafttm.borderxp.Main
name: BorderXP
version: 1.6
api-version: 1.13
author: XCraftTM
website: github.com/XCraftTM/BorderXP

commands:
  bordertoggle:
    aliases: bt
    description: Toggle BorderXP Challenge
    usage: /<command>
  villagetoggle:
    aliases: vt
    description: Toggle Village Spawn in Config
    usage: /<command>